'''
Problem 389: Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

Solution memory usage: 12.8 MB, less than 100% of Python3 submissions
'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        dS = {}
        dT = {}
        
        for c in s:
            if c in dS:
                dS[c] += 1
            else:
                dS[c] = 1
        for d in t:
            if d in dT:
                dT[d] += 1
            else:
                dT[d] = 1
        for key in dT.keys():
            if key not in dS:
                return key
            if dT[key] != dS[key]:
                return key
        
        return ''
